# Generated by Django 2.2.6 on 2019-11-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAPI',
            fields=[
                ('stable_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=255)),
                ('display_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'geneapi_model',
                'db_table': 'gene_autocomplete',
                'managed': False,
            },
        ),
    ]
