# Generated by Django 2.2.6 on 2019-11-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAPITest',
            fields=[
                ('stable_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=255)),
                ('display_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'geneapi_model_test',
                'db_table': 'gene_autocomplete_test',
                'managed': False,
            },
        ),
    ]
