# Generated by Django 2.2.6 on 2019-11-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneapi', '0002_geneapitest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneAPITest',
        ),
    ]
